### ISSUE TITLE
Conversion Funnelling: Separate out the results of conversion goals for further analysis

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#110]
Right now, the 'click on any link' conversion goal in an XB counts any one link that was clicked within the block.
So even if there are multiple links in an XB and only one link was interacted with, there is no way to know which link yielded the results. 

Going forward, we'll want to funnel the interaction with the XB to understand what derive meaningful and actionable insights. 

Combining this with https://altis.invisionapp.com/console/share/RM1XQM3HQJ/496912612, we'll want to surface the results for each link within an XB alongwith the total XB views split by per variant.

eg:

![image](https://user-images.githubusercontent.com/55112796/104761304-b31cfc00-5730-11eb-9694-a1a67a6da604.png)

In this eg, there are two links on 'there' and 'click here'. However, its not clear the conversion result is for which link.

**Comment by PriyaBhatia0210** [comment]
humanmade/product-dev#602

**Comment by rmccue** [comment]
Closing this out until we tackle conversion funnels.
