### ISSUE TITLE
Display uniques instead of views in statistics

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-analytics#126]
XB analytics currently shows all views, and conversion rates are based on this. However, the primary thing I care about is whether a person converted eventually, not whether they did on a specific visit.

We should display uniques as the primary number throughout these statistics instead. (IMO, useful to still show total views in a parenthetical as well.)

**Comment by PriyaBhatia0210** [comment]
This seems like a duplicate of https://github.com/humanmade/altis-analytics/issues/99

**Comment by PriyaBhatia0210** [comment]
Priya to add the UI justy to make it clear

**Comment by PriyaBhatia0210** [comment]
UI for displaying uniques and total views. Suggestions welcome. 

![image](https://user-images.githubusercontent.com/55112796/107074460-c282e880-67b6-11eb-8f44-5772f72b7e20.png)
