### ISSUE TITLE
Show a preview of the XB variant when selected in a page modal

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#127]
**User Story:**
As a content creator, I want to see a quick preview of an XB variant so that I can identify an XB without having to go to the page block editor to see it's title and contents.   

**Requirement:** 
An easy way to recognize an XB when analyzing a page and XB metrics in the Dashboard 

**Acceptance Criteria:**
Given: A modal for a selected page is displayed from the XB dashboard
When: I select an XB from the dropdown list
And: A XB variant is selected from the left hand side list of variants
Then: A preview of that particular XB variant should be displayed in the modal

**Comment by rmccue** [comment]
Closing as a won't do for now.
