### ISSUE TITLE
IE11 users not being tracked

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-analytics#136]
IE11 users aren't being tracked through analytics right now due to the JS being incompatible with IE11. In order to ensure we're tracking all users, we should make sure our JS is compatible with IE11.

The tracking script should be aimed to work on the lowest-common denominator of browsers.

We should update the tracking script to work on IE11 at least. This could be done through polyfills or through the compilation process, or remove the AWS SDK and rewrite with vanilla JS.

----

*Original description:*

![Screenshot 2021-02-18 at 12 08 40](https://user-images.githubusercontent.com/5014023/108354959-15f72c80-71e2-11eb-8af3-b75295c811c0.png)

Noted on a client project using Altis 4. Could not see the same error on the Altis DXP website using Altis 6.

After looking at analytics data, this is causing visits by IE11 users to not be captured.

**Comment by rmccue** [comment]
Altis v4 is no longer supported. Additionally, IE11 is no longer supported by the next WordPress release, and is being phased out generally, so not sure if we want to keep IE11 support.

@sambulance Do you know if the client with IE11 traffic is still getting large amounts of IE11 traffic?

**Comment by sambulance** [comment]
Latest Google Analytics data shows around 1500 hits a month for IE11 (~1% of all traffic). 

As an aside, we are now in the process of upgrading to Altis V7.

**Comment by roborourke** [comment]
The audience numbers aren't always that insignificant depending on the site and user base.

The potential solutions are:

- use something like polyfill.io to patch the missing functionality (need to assess the performance impact and general viability of that) - less effort
- rewrite the analytics.js file to use vanilla JS with IE11 compatibility - high effort

**Comment by shadyvb** [comment]
Polyfill.io uses browser detection to serve polyfills needed, so seemed like the best way forward. Tried adjusting babel, but got a massive bundle and no easy way to split.

**Comment by roborourke** [comment]
Fixed, nice one @shadyvb
