### ISSUE TITLE
Analytics Dashboard: Create a page with a list view of all Experience Blocks 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#137]
Taking a piecemeal approach to building the Dashboard, I am breaking up the development into smaller tasks that I presume we'll have to do anyways to build the end product.

Starting with the list view of all the XBs on a page that can be navigated from the menu under Dashboard.  **The navigation to this page is still under discussion - so ignore this for now.** Use existing styling and markup settings wherever possible. 

**Acceptance Criteria:**
- [x] Create a new page to show a list of experience blocks 
- [x] This page should appear as a sub-page under the Dashboard menu in the Admin below 'my sites'?
- [x] The title of this page should read 'Experience Insights'
- [x] When I navigate to this page, I should see a list of XBs in a table that should have 4 columns
- [x] In the first column, all XBs should be listed by their corresponding titles. The column title should read "Blocks"  
- [x] The XB titles should be a hyperlink to the XB's detailed metrics and fallback comparison which will open into another **[page](https://app.zenhub.com/workspaces/altis-5c378365e15075539771e4e3/issues/humanmade/altis-analytics/138)**
- [x] In the second column, the XBs should have their corresponding total unique views. The column title should read "Views"
- [x] In the third column, the XBs should have their average conversion rate. The column title should read "Avg. Conversion"
- [x] Average conversion rate is calculated as: Total conversions on all variants / Total unique views of all variants for the same time period. (If viewing past 7 days data then consider only past 7 days data for conversions and views of the variants)  
- [x] In the fourth column, the XBs should have their corresponding last modified date and their authors. The column title should read "Last Modified / Author"
- [x] Above the list table, there should be a date range selector pre-defined to 7 days, 30 days and 90 days respectively
- [x] Selecting a date range should modify the XB list table to show data only for the selected time range
- [x] By default, XBs should be listed in the descending order of the total views for the selected date range
- [x] Also, above the table there should be a 'Search' field that allows locating an XB by author, content and title  

  

 

![image.png](https://images.zenhubusercontent.com/5db35a48a7e95f000179f54e/9ae450d9-b711-47b8-a8a8-8d9af233b6ba)

- [x] When I hover my mouse over the column title "Blocks", a microcopy callout should read "List of XBs modified in the selected date range"
- [x] When I hover my mouse over the column title "Views", a microcopy callout should read "Total unique views of the XBs during the selected date range"  
- [x] When I hover my mouse over the column title "Avg. Conversion", a microcopy callout should read "Average conversion is calculated as the total conversion expressed as a % of total unique views of the XB during the selected date range"

**Comment by roborourke** [comment]
Why did we have the last column containing both last modified date and author again?

I've forgotten the discussion around that but it feels odd, the mockup places the author under the block title in the title column.

**Comment by PriyaBhatia0210** [comment]
Hey @roborourke , I took some liberties on design here until we got the final UIs. 

For me, having the Author name and last modified in a separate column makes for a better experience when thinking of adding filters and sorting later on. It also somewhat matches the native WP page list view format. I also thought we could iterate on this should it look too odd and wanted to have some designs ready for the sprint.     

What are your thoughts and why do you think it's odd this way?

**Comment by roborourke** [comment]
Right I see. I guess it seems odd to me because these values aren't grouped anywhere else in WP or other UIs that I've seen. The modified date is a sortable field typically, or a field that's easy to make sortable, so having both the author and date in the one column could make it confusing. If I sort by that column then what am I sorting by? Modified date? Author? Both?

We could put the author in its own column if it's something we'd want to add filters or sorting on later if that's the intention.

**Comment by PriyaBhatia0210** [comment]
Yeah the intention was to be able to sort by the author. Modified date below Author name was just to read as a microcopy to let the user know what is the last XB they worked on / modified. 

I _don't_ think a sort by modified date would be required. That leads me to another question: How is the XB list being presented right now? Is it in a descending order of best performing XBs or the most recent ones on the top?

**Comment by roborourke** [comment]
It should be defaulting to views in descending order, then you could sort by modified date, or conversions or something else.

I think in the acceptance criteria it reads as the date coming first and being more important. Either way I’m not sure how intuitive this is. I vote we just have those things in separate columns for now.

**Comment by jazzsequence** [comment]
The default is to order descending by views with block name, views and conversions all being sortable columns.

IMO, if the modified date/author is _not_ sortable, then I don't have a problem with combining them as that is the _least_ interesting piece of data in the list. However, if the intent was/is to allow sorting by either of those datapoints, they should definitely be separate columns.

Personally, I was wondering a bit about the block "author" in relation to "last modified date" -- an author may have _created_ the block, but it's possible that they weren't the ones who _last modified_ it. Which could make the inclusion of author here or the combination of both things a bit confusing.
