### ISSUE TITLE
Analytics Dashboard: Navigate to per block metrics from the list of XBs in the Experience Block Analytics page

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#138]
_(Updated)_
Taking a piecemeal approach to building the Dashboard, I am breaking up the development into smaller tasks that I presume we'll have to do anyways to achieve the end result.

The next step after building the Experience Block Analytics page is navigation to per block metrics. 
(Note:  Use existing styling and markup settings wherever possible.)

**Acceptance Criteria:**
- [x] Create a new page to display per block metrics. 
- [ ] When I click on the hyperlinked title of an XB in the list view of [Experience Block Analytics](https://app.zenhub.com/workspaces/altis-5c378365e15075539771e4e3/issues/humanmade/altis-analytics/137) page, I should be directed to this page.
- [x] Heading 1 of this page should read "Experience Insights"
- [x] Heading 2 of this page should display the Title of the selected XB (**The title is not editable in this page. Ignore the design in the picture**)
- [x] Next line of the page should be a date range selector - This should be the same as the one described on the Experience Block Analytics page - should be pre-defined selector for 7 days, 30 days and 90 days of data
- [x] Selecting one of the 3 date ranges should modify rest of the page data
- [x] Next the page should display 3 major cards/blocks of data:
- [x] The first block should read "Block Views" and should display total unique views of all the variants of the XB. Its microcopy should read "Total number of times this block has been viewed by new visitors to the website"
- [x] The second block should read "Average Conversion Rate" and should display the average conversion rate of all variants. It's microcopy should read "Average conversion of the block as a percentage of total unique views of the block" 
- [x] Average conversion rate is calculated as: Total conversions on all variants / Total unique views of all variants for the same time period. (If viewing past 7 days data then consider only past 7 days data for conversions and views of the variants)  
- [ ] Leave the third card of data blank for now
- [x] Below the three cards, list the variants of XBs starting with the Fallback variant. Below the title of Fallback variant, display its total views and conversions with corresponding microcopy as shown in the picture. 
- [x] The Fallback variant is followed by other personalized variants of the block. Below the title of the variant, display its total views,  conversions and audience size  with its corresponding microcopy as shown in the picture. 
**Ignore the right column alongside the list of variants**     

Note: For the purpose of the MVP we are ignoring the icons and stylistic parts of the design because we want to keep these things consistent and have a component library of sorts to start incorporating them in the features.  

![image.png](https://images.zenhubusercontent.com/5db35a48a7e95f000179f54e/b6cd26b6-c420-472f-9cae-6a7427e5267e)

**Questions:**
1. Should microcopy be made available on "learn more", on hover or on the card itself?
2. What happens when the conversion of Fallback is higher than the personalised content? Just because the audience size is larger? The 'Lift' metrics would not drive the point home.
3. If I have to think about 'audience coverage' how does that work? Can we predict the traffic that a website will get and hence what is being currently covered with the audience segmentation?
4. Thinking about the third card: how could this be calculated? Does this mean the total audiences that are being personalised from the total audience visiting the website?

**Comment by roborourke** [comment]
> 1. Should microcopy be made available on "learn more", on hover or on the card itself?

Hover isn't a guaranteed interaction, click is more reliable across different platforms & devices. I think if we know what we want to say in there we can just show a message box under the block title before the cards with the info.

> 2. What happens when the conversion of Fallback is higher than the personalised content? Just because the audience size is larger? The 'Lift' metrics would not drive the point home.

The size of the audience won't matter if we show percentages, and if the lift is negative for personalised content then it just means those aren't the audiences to target or the content needs work I suppose. We can't guarantee it'll perform better, just that it can be measured.

> 3. If I have to think about 'audience coverage' how does that work? Can we predict the traffic that a website will get and hence what is being currently covered with the audience segmentation?

With a large enough sample size of existing data some predictions could be made but I think this just needs to reflect the last 7 days of traffic. Perhaps we could think about indicating if there's not enough data yet then it might not be accurate.

> 4. Thinking about the third card: how could this be calculated? Does this mean the total audiences that are being personalised from the total audience visiting the website?

Yeah that would do it. I think that could be inferred from total views of personalised variants vs total views of fallback.

**Comment by PriyaBhatia0210** [comment]
Thanks Rob. Let's chat a little about these questions in the refinement tomorrow.
