### ISSUE TITLE
Trash label on Audiences should say Delete Permanently

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-analytics#142]
When hovering over an audience on the Audiences screen, the delete button says "Trash" but this is actually a permanent action. It should say "Delete Permanently" which is inline with the list view of the Media screen.

**Comment by rmccue** [comment]
Urgh yeah, this annoys me to no end, but I think it actually _does_ trash, it's just that the trash isn't viewable anywhere?

**Comment by rmccue** [comment]
Duplicate of https://github.com/humanmade/aws-analytics/issues/169
