### ISSUE TITLE
Environment constants not set

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#18]
In Cloud at least, I see the following:

```
Altis Analytics: Missing configuration. 	You must define the following constants in PHP:
 	define( 'ALTIS_ANALYTICS_PINPOINT_ID', '...' );
 	define( 'ALTIS_ANALYTICS_PINPOINT_REGION', '...' );
 	define( 'ALTIS_ANALYTICS_COGNITO_ID', '...' );
 	define( 'ALTIS_ANALYTICS_COGNITO_REGION', '...' ); 	
```

@roborourke I'm not sure how these constants are meant to be defined in Cloud. I don't see this module setting them or Cloud.

**Comment by roborourke** [comment]
@joehoyle I thought they'd come from the production config in our case. I'm not sure how to access cloudformation outputs

**Comment by roborourke** [comment]
@faishal is this something you can pick up?

**Comment by faishal** [comment]
@joehoyle / @roborourke 

We already have all that constants defined in wp-config via env variable but name are different: https://github.com/humanmade/terraform-app-stack/blob/master/files/php-environment.json#L123
```
AWS_COGNITO_IDENTITY_POOL_ID
AWS_COGNITO_IDENTITY_POOL_REGION
AWS_MOBILE_ANALYTICS_APP_ID
AWS_MOBILE_ANALYTICS_APP_REGION
```
Let me know if you want to rename it.

**Comment by joehoyle** [comment]
@faishal can you rename those to match the constants I put in the description?

**Comment by faishal** [comment]
Updated in https://github.com/humanmade/terraform-app-stack/pull/213

**Comment by joehoyle** [comment]
Done!
