### ISSUE TITLE
Create editor for A/B testing block type

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-analytics#190]
Part of humanmade/product-dev#812

We want to add a new A/B testing block type to the block editor. This block should operate similarly to our existing personalisation block, with multiple "variants" of the same piece of content; we can copy the code for this this from the existing block.

![](https://user-images.githubusercontent.com/21655/137166261-ecbe528a-a72f-4484-a06a-9d1aa7647f40.jpeg)

This block should have some overall settings, and some per-variant settings.

![](https://user-images.githubusercontent.com/21655/137736113-201f9e05-5d4a-4942-a4ab-899679d8029c.jpg)

Acceptance criteria:
* [x] Author can create an A/B testing block within the block editor
* [x] A/B testing block appears under "Experience Blocks" category
* [x] A/B testing block allows adding multiple variants
* [x] A/B testing block allows per-variant settings for title, weighting, and conversion goal
* [x] Block is registered with experiments API when it is created

**Comment by roborourke** [comment]
Got a PR up ready for review that checks the boxes here but there are few more things we might need to consider or just spin out a separate issue for:

- Advanced settings e.g. start & end dates, which ones might we want and when should they be updated, on publish or dynamically
- Any considerations around use within reusable blocks
- How to handle winning variants, e.g. bypass the custom component and output the variant directly or provide the winning variant information to the block as an attribute
