### ISSUE TITLE
Surface A/B testing blocks in the Insights view

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-analytics#191]
In the same way we have UI to show the personalised content block analytics data, we need to show how an A/B test is performing and what the outcome was.

This will use the same template as the existing personalised content insights screen with the following differences:

- remove the top line metrics
- remove the audience coverage metric
- add a data point per variant row to indicate if the change is statistically significant or not
- add an indicator if a particular variant is the winner

Acceptance criteria:

- [ ] Insights view should be able to be opened in a popup from the block settings sidebar

**Comment by roborourke** [comment]
> I kept the variants view similar to what we already have with personalization, but I actually think a table view might be better for this, with the variant name as the first column rather than as a header. This would be closer to the views exposed by alternative tools that users are likely to be familiar with.

That might actually be better for the personalisation view too tbh.

I think this'll work. Are those top line metrics aggregate for all variants again? Or for the winner? Would they change at all?

**Comment by yumito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Altis-5c378365e15075539771e4e3/issues/humanmade/altis-analytics/191?planning-poker) with ZenHub @robindevitt @roborourke @shadyvb
