### ISSUE TITLE
Expose A/B test block data via REST API

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-analytics#195]
There is an existing API endpoint for personalised content blocks at `/wp-json/analytics/v1/xbs/<clientId>`, the data structure is specific to personalised content currently but should be able to show or embed A/B testing data as well.

A/B test data is available from the XB post REST API response. The same output should be available through the XB analytics endpoint.

Acceptance criteria:

- [ ] Responses from `/wp-json/analytics/v1/xbs/<clientId>` should include the XB type (personalised or ab test)
- [ ] Responses for AB test blocks from `/wp-json/analytics/v1/xbs/<clientId>` should include the same data as personalised content with the following additions:
   - winning variant
   - indicator of whether change is statistically significant
   - relative weight of each (likely already there)
   - any other data determined via #196

**Comment by rmccue** [comment]
Per @roborourke, this A/B testing data is likely already in the API data, so this may not be required.

**Comment by roborourke** [comment]
Looked again at what gets output right now, as an example:

```
"ab_tests": {
    "xb": {
      "started": false,
      "start_time": 1636629941000,
      "end_time": 1639221941000,
      "traffic_percentage": 0,
      "variant_traffic_percentage": [
        ""
      ],
      "paused": true,
      "results": {
        
      }
    }
  },
  "subtype": "altis/ab-test",
  "variants": [
    {
      "fallback": true,
      "percentage": 47,
      "title": "Default"
    },
    {
      "fallback": false,
      "percentage": 7.725428241649752e-7
    },
    {
      "fallback": false,
      "percentage": 0.0000010406757514392205
    }
  ],
```

So we're covered on the XB type via the `subtype` property, and we have the AB test data output from registering the test. There does seem to be some error in the stored data right now, I think from some work in progress though.

Anyway, upshot is that the data is exposed already, so closing out.
