### ISSUE TITLE
OG title messed up due to experiment

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#20]
This is on a default Altis setup:

```

<meta property="og:title" content="	&lt;ab-test
--
  | test-id=&quot;titles&quot;
  | post-id=&quot;1&quot;
  | traffic-percentage=&quot;100&quot;
  | goal=&quot;click&quot;
  | variant-count=&quot;2&quot;
  | &gt;
  | &lt;test-fallback&gt;Hello world!&lt;/test-fallback&gt;
  | &lt;test-variant&gt;
  | Hello world!		&lt;/test-variant&gt;
  | &lt;test-variant&gt;
  | Goodbye Earth!		&lt;/test-variant&gt;
  | &lt;/ab-test&gt;
  | " />


```

**Comment by roborourke** [comment]
There's a few approaches we could take to this:

- ensure the titles filter runs after the `wp_head` action
- set context helpers, eg. if upstream `esc_attr()` is called then don't output the markup
- backtrack entirely to a single wrapper element with the variants encoded in a data attribute

I'm not a super fan of any of these really but the last one seems like the right one to implement. In most cases the output should be put through `strip_tags()` or similar.

Will need to update the `meta-tags` plugin too to run `wp_strip_all_tags()`.

**Comment by roborourke** [comment]
Ok got 2 PRs to merge so far for this:

- [ ] https://github.com/humanmade/meta-tags/pull/7 - strip tags in meta tag output
- [ ] https://github.com/humanmade/experiments/pull/15 - use a single element for tests with variants in an attribute

`meta-tags` will need to be tagged as 0.1.6 after merge then given the current version constraints we should be good. Can always update those too if desirable.
