### ISSUE TITLE
SPIKE: Altis Analytics Export

### ISSUE THREAD

**Issue by robindevitt** [humanmade/altis-analytics#206]
Exporting large amounts of data with the following url `/wp-json/analytics/v1/events/2021-12-09?format=json` present's two issues:
1. The API can be slow.
2. The API sometimes fails.

### Expected to see:
An export without any errors or failures.

### Acceptance criteria:

- [ ] An export without any errors or failures.

**Comment by shadyvb** [comment]
@robindevitt Seems more of a spike than an issue ?

**Comment by roborourke** [comment]
We can close this out, I reproduced the issue and created some issues on the aws-analytics repo.

Ultimately ES is the bottleneck and it depends on the amount of data being requested, more data than ~60k rows of data fails consistently but it fails earlier than that inconsistently depending on how busy the site is.

See:

- https://github.com/humanmade/aws-analytics/issues/320
- https://github.com/humanmade/aws-analytics/issues/319
- https://github.com/humanmade/aws-analytics/issues/318
- https://github.com/humanmade/aws-analytics/issues/317
