### ISSUE TITLE
New posts default to started empty experiment

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#21]
Any post that doesn't have a running experiment appears to start with a blank one, then when you click "Start an Experiment" you can an alert saying "do you want to wipe the current test", but there was no test... because this is a new post.

![](https://joehoyle-captured.s3.amazonaws.com/82smOns4.png)

**Comment by joehoyle** [comment]
This is fixed upstream.

**Comment by rmccue** [comment]
Fixed in https://github.com/humanmade/altis-analytics/pull/22
