### ISSUE TITLE
Fail gracefully if config values are not found.

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-analytics#234]
There is a check for the configuration option for enabling/disabling the new dashboard page, that seems to cause a notice if the client has overridden the default config and has not included the `dashboard` config property in `composer.json` config.

The notice message is:

```
E_NOTICE Undefined index: dashboard in /usr/src/app/vendor/altis/analytics/inc/native/namespace.php:24
```

Reference https://github.com/humanmade/altis-analytics/blob/master/inc/native/namespace.php#L24

### Acceptance criteria
- [x] When using custom config for the Analytics module in `composer.json` while omitting the `dashboard` config property, no notice should be generated in PHP logs.

**Comment by roborourke** [comment]
Fixed in #235
