### ISSUE TITLE
Pagination in Altis dashboard needs wrapping

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-analytics#239]
Steps to reproduce:
1. Add many pages worth of posts, say 1000
2. Notice how the pagination links are not wrapped and go outside visible screen.

Pagination links container should be wrapped.

![t28cOD](https://user-images.githubusercontent.com/451892/157015083-04873af5-6021-4550-bd89-6da30666fa50.png)

Acceptance criteria:

- [x] Pagination links container in Altis dashboard should be wrapped.
- [x] Maximum of 10 page number links shown at one time
- [x] Always show first page and last page link
- [x] Show 3 pages either side of current page (if available)
- [x] Show an empty placeholder between the first page and last page links when some page numbers are skipped
- [x] Next page link shows after page numbers on all except last page
- [x] Prev page link shows before page numbers on all except first page
- [x] An input that allows you to jump to a particular page

It was noted that adding `flex-wrap:wrap;` to the container should help fix the bug.

**Comment by roborourke** [comment]
Adding some additional Acceptance Criteria:

- [ ] Maximum of 10 page number links shown at one time
- [ ] Always show first page and last page link
- [ ] Show 3 pages either side of current page (if available)
- [ ] Show an empty placeholder between the first page and last page links when some page numbers are skipped
- [ ] Next page link shows after page numbers on all except last page
- [ ] Prev page link shows before page numbers on all except first page

Some examples based on having 250 total pages:

- If I'm on page 1 show:   `1  2  3  4  ...  250  next >`
- If I'm on page 4 show:   `< prev  1  2  3  4  5  6  7  ...  250  next >`
- If I'm on page 12 show:   `< prev  1 ... 9  10  11  12  13  14  15   ...  250  next >`
- If I'm on page 249 show:   `< prev  1  ...  246  247  248  249  250  next >`
- If I'm on page 250 show:   `< prev  1  ...  247  248  249  250`

Hope that makes sense - please feel free to suggest any changes / improvements.

**Comment by rmccue** [comment]
FYI, WordPress has a `paginate_links` helper you can use:

```php
	$page_links = paginate_links( array(
		'base' => 'base_url?paged=%#%',
		'format' => '',
		'prev_text' => $args['prev_text'],
		'next_text' => $args['next_text'],
		'total' => $number_pages,
		'current' => $current_page,
		'mid_size' => $mid_size,
		'end_size' => 1,
		'show_all' => $args['show_all'],
		'type' => 'array'
	) );
```

**Comment by roborourke** [comment]
Does it have a similar thing for React?

Maybe we can grab one these components:

- https://mui.com/components/pagination/
- https://www.npmjs.com/package/react-paginate

Or just roll our own.

**Comment by robindevitt** [comment]
In a use case where a user has 200+ pages on their site. Pagination will start "1 2 3 4 ... 398 399 400" for example. If the user was needing to navigate to page 150, they would need to click through roughly 147 times until they can click page 150, would having an option for a user to select a page or input a page number to navigate to quickly be useful too?

In Posts in WordPress you can navigate to the previous/next, first/last or specify a page number to navigate too.

I have come across https://www.npmjs.com/package/react-pagination-bar which has some options too, as well as the option for an input to navigate to a specific page : https://react-pagination-bar.vercel.app/

**Comment by roborourke** [comment]
@robindevitt good shout, the default WP pagination is like this so I think it's good to add the option with a go to input. Do you want to update the acceptance criteria?

**Comment by robindevitt** [comment]
Looking through the two packages, trust the one package to have functionality that the other one doesn't.
[react-pagination-bar ](https://www.npmjs.com/package/react-pagination-bar) has the the input functionality but doesn't offer the option to have `1 2 3 4 ... 250` with the ellipses in-between, so I'm going to see if I can find a package that contains both options/possibilities.

**Comment by robindevitt** [comment]
@roborourke I'm leaning towards using a package to get this done as at the moment it's a single use case. If we were using it multiple times over then I would say to develop our own pagination component.

[rc-pagination](https://www.npmjs.com/package/rc-pagination) - Ticks all the boxes, unpacked size 157 kB

[react-pagination-bar](https://www.npmjs.com/package/react-pagination-bar) - Doesn't tick all the boxes is the sense of that it doesn't have an option to show pagination like - `1 2 3 4 ... 250`. However its unpacked size is 72.6 kB.

I think implementing `rc-pagination` based on acceptance criteria would be good start unless we would want a smaller package and compromise on acceptance criteria?
