### ISSUE TITLE
Load analytics library async.

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#24]
Do we _really_ need the analytics library to be loaded sync in the header?

We are getting hurt by it on https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Faltis-dxp.com&tab=mobile. I can see Experiments making sense, but the analytics one maybe not?

**Comment by roborourke** [comment]
Yeah i think experiments requires some analytics features though to work. I’d like to get a global service worker solution in place really.

There’s a definite requirement for load order to be respected so I’ll do some testing.

**Comment by roborourke** [comment]
Opened humanmade/analytics#25 to track upstream.

**Comment by roborourke** [comment]
PR ready here: https://github.com/humanmade/analytics/pull/26

**Comment by roborourke** [comment]
Done.
