### ISSUE TITLE
Segment integration QA & functional testing

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-analytics#246]
Follow on from https://github.com/humanmade/altis-analytics/issues/220 to perform further testing and QA.

https://docs.altis-dxp.com/nightly/analytics/native/api/data-export/segment/

Acceptance criteria:
 - [x] create a shared development Segment account and add it to 1password
 - [x] configure platform test with Segment API key
 - [x] check that all analytics events are successfully delivered (click around the site, generate some events and check Segment within 10 minutes for events)

**Comment by veselala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Altis-5c378365e15075539771e4e3/issues/humanmade/altis-analytics/246?planning-poker) with ZenHub @mikelittle @robindevitt @roborourke

**Comment by roborourke** [comment]
Can this be closed now @shadyvb ?

**Comment by shadyvb** [comment]
Not until I verify the data is actually being submitted, need to redeploy the test stack and check after the aws-analytics 4.6 version is released with the changes needed.
