### ISSUE TITLE
Disabling Workflow module causes Uncaught Error 

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-analytics#27]
So when you disable the Workflow module in Altis the following error is returned:
```
Uncaught Error: Class 'HM\Workflows\Event' not found in /chassis/vendor/altis/analytics/inc/native/namespace.php on line 70

    Altis\A\N\setup_notifications()
    wp-includes/class-wp-hook.php:286
    apply_filters()
    wp-includes/class-wp-hook.php:310
    do_action()
    wp-includes/plugin.php:465
    do_action()
    wp-settings.php:394
    require_once()
    wp-config.php:67
    require_once()
    wp-load.php:42
    require_once()
    wp-admin/admin.php:34
    require_once()
    wp-admin/edit.php:10
```

From my understanding this is the issue:
https://github.com/humanmade/altis-analytics/blob/master/inc/native/namespace.php#L70

We should do either of the following:
- Check to see if the Workflow module is active and do the notifications, if it's not active to do nothing
- If notifications are a requirement, possibly just setup a basic fallback to be WP_Mail, to default email in WordPress?

**Comment by roborourke** [comment]
Thanks @stuartshields, it does have a default `wp_mail` handler in the experiments plugin so I'll make sure we're not relying on the other module entirely.

**Comment by roborourke** [comment]
@stuartshields I've backported this fix to v2 so you can get the latest by running `composer update`
