### ISSUE TITLE
Consistent naming of A/B testing

### ISSUE THREAD

**Issue by sambulance** [humanmade/altis-analytics#30]
Throughout the documentation, A/B testing is referred to as both "A/B" and "AB" testing. We should pick one and use it consistently.

<img width="737" alt="Screenshot 2019-11-19 at 11 17 49" src="https://user-images.githubusercontent.com/5014023/69142376-90586e80-0abe-11ea-9d48-703fe9265134.png">

https://www.altis-dxp.com/resources/docs/analytics/
https://www.altis-dxp.com/resources/docs/analytics/experiments/
https://www.altis-dxp.com/resources/docs/guides/upgrading/v2/

Note: The "A/B" is used in the actual UI:

<img width="289" alt="Screenshot 2019-11-19 at 11 55 02" src="https://user-images.githubusercontent.com/5014023/69144570-7705f100-0ac3-11ea-9432-175ff7ca1e91.png">

-----------

Acceptance criteria:

- [ ] All instances of "AB" should be updated to "A/B" for consistency in the docs.

**Comment by rmccue** [comment]
I think AB testing is what you do at the gym 🤔
