### ISSUE TITLE
Dashboard Scaffolding

### ISSUE THREAD

**Issue by noeltock** [humanmade/altis-analytics#314]
![Accelerate Dashboard.jpg](https://images.zenhubusercontent.com/5498172e7c6ccc6277a6b673/83a7f431-fd78-4f7f-beaa-09ca16d09092)

This issue is for the Dashboard, comments:

- The overall design [can be found here](https://www.sketch.com/s/5a025e5d-5a9e-4e8f-8d19-5c9bde5c0564/a/MyVxwLm). 
- Two components/epics will be added inside of it (see those issues for those components):
  - Hero Chart #1081
  - Content Explorer #1076
- We will migrate the default WP dashboard to a sub-menu item at the top of the dashboard tab in the WP side nav, called "Widget Dashboard", open for suggestions.
- The scaffolding includes a meta header which has logo, our own navigation (external links) and current release version).
- Welcome text (as per design) with link to Widget Dashboard.

**Comment by noeltock** [comment]
Assigning to @roborourke for review

**Comment by roborourke** [comment]
Looks good overall. I'd like to go deeper on some items though, and also to get clarity on what is shippable right now to avoid questions / confusion.

Some of the questions below can perhaps be answered on the specific issues rather than here.

To that end:

- What links will we have under the author avatar & name
- What is the UI once "Add new" is clicked
- After the content type there is text like "Spring Promo", what is the source of that
- There are only positive percentage change indicators shown, what does the opposite look like
- Are there hover/focus states
- Does the hero chart show uniques or total page views, should we show both?

**Comment by shadyvb** [comment]
Also:

- How would pagination look like for the table items. Shall we stick with what we currently have ?

**Comment by noeltock** [comment]
> What links will we have under the author avatar & name

We have no _special actions_ for now (as the features aren't there to go clickthrough to). So I think Edit, Duplicate, Archive is it — however Duplicate/Clone doesn't exist as functionality yet, so that could be backlogged (and simply ship Edit/Archive).

> What is the UI once "Add new" is clicked

Good shout, I'll get that designed/mocked-up, but will be a dropdown of content types (Post, Page, Block, etc)

> After the content type there is text like "Spring Promo", what is the source of that

"Spring Promo" specifically was exploratory design, apologies for including that — it reflects a potential future where we have another Campaign layer/feature. That aside, open to thoughts, but my idea was:

- Page: "[Post Type] /  [Category]", i.e. `PAGE / SERVICES`
- Post: "[Post Type] /  [Pretty Age]", i.e. `POST / 17D OLD`
-  Block/Misc: "[Post Type]", i.e. `REUSABLE BLOCK` _// this is where Campaign can come in as secondary meta here in the future_

> There are only positive percentage change indicators shown, what does the opposite look like

Snap, will get that done, cheers.

> Are there hover/focus states

Nothing exotic, if I have time, I'll get the designs to reflect the subtle changes in colour for hovers.

> Does the hero chart show uniques or total page views, should we show both?

Uniques, this was a Greece convo, but the assumption being that we want to start with Users as that's the currency of DXP's, so we're helping frame/prime our users to actual visitors as opposed to a supply of pageviews. Regarding doing both, we discussed our users having to request that from us (i.e. we start small). Once we get there, there'll be additional design work too (shadow line, secondary line, etc.).

> How would pagination look like for the table items. Shall we stick with what we currently have ?

Yeah, let's roll with that for now 👍🏻 Ping in Slack if you need advice/thoughts on the fly. Cheers!

**Comment by roborourke** [comment]
> So I think Edit, Duplicate, Archive is it — however Duplicate/Clone doesn't exist as functionality yet, so that could be backlogged (and simply ship Edit/Archive)

"Archive" isn't language used by default in WP anywhere with regards to content, at least in english language packs. Would that be equivalent to "Trash"? Although I do prefer the term "Archive" to "Trash" it'd be better to match default WP terminology.

Cheers for the other clarifications.

**Comment by shadyvb** [comment]
Assigning back to @noeltock to progress as per convo.

**Comment by shadyvb** [comment]
Remaining from the tasks outlined in OP is the meta header and welcome text.

>- The scaffolding includes a meta header which has logo, our own navigation (external links) and current release version).
>- Welcome text (as per design) with link to Widget Dashboard.
