### ISSUE TITLE
Onboarding videos tracking on Mixpanel

### ISSUE THREAD

**Issue by veselala** [humanmade/altis-analytics#317]
As part of the product team I want to be able to track if a given user has watched the onboarding video for each future that we have so that I can serve them with specific notifications/ AppCues.

For the initial release we will have one onboarding vide (@noeltock correct me if I'm wrong), but on a later stage we assume that we will have a specific for each new feature that we introduce. The idea is that AppCues can be triggered based on event rules. As we want to serve our new users with relevant information we need to be able to distinguish if they've watched the video or not. We assume that if the video was not played this is the first time a given user has logged in.
@roborourke I'm not quite sure how can we connect the firing of this event with a given user and use it on a next login, so maybe some input from you will be helpful. As discussed on a previous meeting with @noeltock  we want to show the video to users that haven't seen it.

_Updated as per @noeltock comment below:_

Mixpanel event:

- [ ] Onboarding video played - should track when the onboarding video is being played on the WordPress dashboard for the user or it's initialized by the user form the _User guide section_

**Comment by veselala** [comment]
I guess this is howe we can build and Audience based on that event to trigger the AppCue https://docs.appcues.com/article/450-event-triggering#:~:text=Set%20up%20the%20event%20trigger,from%20the%20drop%2Ddown%20menu.

**Comment by veselala** [comment]
From today's Accelerate meeting was clear that we still don't know where the video will be activated (SaaS or admin dashboard). so we still have no idea what event will it be triggered by. Waiting for @noeltock to confirm.

**Comment by roborourke** [comment]
@noeltock I think this is a high priority right now - are you handling setting this up or do you need to hand it off?

**Comment by noeltock** [comment]
Joe added the events to the Notion page. Can you please ensure correctness @veselala ? Thanks

**Comment by veselala** [comment]
_Onboarding Video Played_ event is on Notion, but not marked as implemented

I also don't see all the "welcome" events coming into Mixpanel, that are marked as implemented.
@joehoyle could you please check what's going on?
