### ISSUE TITLE
Undefined index on first start

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-analytics#52]
![image](https://user-images.githubusercontent.com/21655/84915871-43b92e00-b0b5-11ea-9cfc-45224486533c.png)

I'm not sure exactly what the value of $result here is, but I suspect it's an uninitialised index of some sort?

**Comment by rmccue** [comment]
Aha, it's simply if there's no results:
```
array(4) {
  ["took"]=>
  int(0)
  ["timed_out"]=>
  bool(false)
  ["_shards"]=>
  array(4) {
    ["total"]=>
    int(0)
    ["successful"]=>
    int(0)
    ["skipped"]=>
    int(0)
    ["failed"]=>
    int(0)
  }
  ["hits"]=>
  array(3) {
    ["total"]=>
    int(0)
    ["max_score"]=>
    float(0)
    ["hits"]=>
    array(0) {
    }
  }
}
```

**Comment by rmccue** [comment]
I guess this is fixed now as our dep version is relaxed, but should we bump the minimum ver to 2.2.2 @roborourke?

**Comment by roborourke** [comment]
@rmccue can do, was hoping dependabot would just sort that out :)

**Comment by rmccue** [comment]
I don't think it'll do anything; it won't bump the constraint (because it's still current), and there's no lock file.

**Comment by roborourke** [comment]
derp, I'll make a PR
