### ISSUE TITLE
Add block transforms for XBs

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-analytics#69]
To make personalisation even easier, we should add the ability to turn any block into an XB, while preserving the content. This can be done via [block transforms](https://developer.wordpress.org/block-editor/developers/block-api/block-transforms/) in Gutenberg.

The workflow for personalising any block would then simply be:

1. Select block (or blocks, if block transforms support multiple blocks)
2. Transform to XB. Previous content becomes the fallback automatically.
3. Copy the variant to a new variant
4. Adjust new variant with audience and content changes

This should apply to all blocks, and if possible, to selecting multiple blocks at once too.

We do not need to add the reverse (converting from personalized content to non-XB).

Acceptance criteria:
- [ ] When I select a non-experience block, I see a "Transform to Personalized Content" option on the block menu (under "Transform")
- [ ] When I select multiple non-experience blocks, I see a "Transform to Personalized Content" option on the block menu (under "Transform")
- [ ] When I select an experience block, I should **not** see the "Transform to Personalized Content" option.

**Comment by roborourke** [comment]
Closed in humanmade/aws-analytics#234
