### ISSUE TITLE
XB Analytics: Provide a way to allow users to set a conversion goal within experience blocks

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#76]
From XB Analytics Discussion in Platform Services repo:

## User Story
As a content creator, I'd like to create a CTA as a part of my XB to be set as a conversion goal, so that I can objectively track the way the XB performed with my audience

## Requirements
1. The ability to quickly create a CTA that is visibly clear in the /wp-admin/
2. The ability to set a conversion goal event for the CTA (CTA Conversion Goals below)  

### CTA Conversion Goal Options
View
Outbound Link
Form Submission

## Acceptance Criteria
Given: I am in wp-admin using XBs for my content creation
When: I create an XB variant
And: assign an audience
Then: I should be prompted to add a CTA and conversion goal to the XB
And: I should later be able to see how the selected audience interacted with the CTA

**Comment by PriyaBhatia0210** [comment]
Starting to scribble the UI prompt for CTA creation

![image](https://user-images.githubusercontent.com/55112796/97055581-1691f600-1555-11eb-8a36-ece6c239455b.png)

**Comment by roborourke** [comment]
Where you suggest changing to "Block 1" I did have that title as "Variant 1" previously. I was thinking that when clicking the button it could open the audience selection modal so it's easier to see what you need to do and it can be triggered inline.

**Comment by rmccue** [comment]
Assuming these CTAs will also likely need to be set for each variant individually rather than overall.

**Comment by PriyaBhatia0210** [comment]
> Where you suggest changing to "Block 1" I did have that title as "Variant 1" previously. I was thinking that when clicking the button it could open the audience selection modal so it's easier to see what you need to do and it can be triggered inline.

@roborourke Sounds even better. I can draw up the UI if we agree. 

> Assuming these CTAs will also likely need to be set for each variant individually rather than overall.

Correct. Therefore, the overall title on the right hand side bar is "Personalize Block 'X' " when it is selected. I like Rob's idea too.

**Comment by roborourke** [comment]
> > Assuming these CTAs will also likely need to be set for each variant individually rather than overall.
> 
> Correct. Therefore, the overall title on the right hand side bar is "Personalize Block 'X' " when it is selected. I like Rob's idea too.

That's not what we decided as I understood it. It would be much clearer and straight forward from a UI perspective to set a conversion goal at the XB level rather than the variant level because you're not really making a valid comparison otherwise. The piece you might be missing @rmccue is that we can validate whether the variants meet the conversion goal requirement.

**Comment by rmccue** [comment]
@roborourke Right, but I would think you would need to specify per variant what exactly the specific CTA is.

Imagine I have two variants: one is a link to our external partner in Japan, and the other is a button to contact us directly. Two separate actions with no common technical aspect, but either of those counts as the viewer "converting". (In a future with XBs for testing instead of just personalisation, you can also imagine the same applying to an A/B test with different elements in each variant.)

An overall goal (e.g. "get 30% of people to convert") could make sense at an XB level, but specifying the CTA itself I think has to be per variant.

**Comment by roborourke** [comment]
The ability to set a conversion goal on any block even outside of the XB context is something I considered would be useful as long as we can surface the data somewhere. We could get both doing it this way.

I think my issue is the framing around comparing how variants are performing. If they're very different then my concern is that any comparison could be misleading, especially if the audiences vary in size a great deal or aren't mutually exclusive. What if the conversion goal for one variant is just the default view and another is a click on something.

Either way, we can go with the approach you suggest @rmccue, I'd just suggested otherwise because it's going to be much harder and potentially confusing given how the editor sidebar changes to reflect the block you're currently editing and loses the XB context.

**Comment by PriyaBhatia0210** [comment]
>Imagine I have two variants: one is a link to our external partner in Japan, and the other is a button to contact us directly. Two separate actions with no common technical aspect, but either of those counts as the viewer "converting". (In a future with XBs for testing instead of just personalisation, you can also imagine the same applying to an A/B test with different elements in each variant.)

This is exactly the approach I was going for and assumed we were on the same page. My bad if this wasn't communicated well in our discussion. But this is crucial just from the standpoint of flexibility and extendibility in the hands of a user to be able to use a CTA they want that can be different for different use cases. (I was using Docusign yesterday (bad example may be) but even though I specified in the beginning that i would need two signatories, I was prompted to select the field (CTA) I would like for each signatory SEPARATELY. This is because, I might want to change the placement/ type of signature, etc. But that gives back so much control to me as a user.)  

>I think my issue is the framing around comparing how variants are performing. If they're very different then my concern is that any comparison could be misleading, especially if the audiences vary in size a great deal or aren

Exactly. This is a good point which I agree to. Hence, if you see the [metrics to track](https://github.com/humanmade/altis-analytics/issues/78) issue, we will try to compare a personalised XB variant to a non-personalised one which is the fallback variant. This will potentially tell a user using the conversion metrics how a personalised XB performed vs a non-personalised one.
 
> Either way, we can go with the approach you suggest @rmccue, I'd just suggested otherwise because it's going to be much harder and potentially confusing given how the editor sidebar changes to reflect the block you're currently editing and loses the XB context.

Probably a good place to seek the Designer's help we are hoping to bring for Altis?

**Comment by roborourke** [comment]
Hmm, at the moment XBs are completely flexible. The fallback could legitimately contain nothing. What if one variant has a conversion goal and another doesn't? Does that matter?

**Comment by PriyaBhatia0210** [comment]
> What if one variant has a conversion goal and another doesn't?

In this case, i am thinking about what you said that the no. of views could be a default conversion goal. However, I'd imagine we want to prompt users to add an explicit conversion goal for their own benefit of targeting their customers with personalised content. 

> The fallback could legitimately contain nothing

I'd like to believe, there will always be a fallback content. For a marketer, the fallback content is their non-personalised generic content that they use today in absence of an XB capability. They can only build so much personalised content and then have some generic content. 
That's kind of the whole premise of building XBs - that personalised content performs better for targeting end customers vs non personalised content and that is exactly what we want to surface to the users in form of data and metrics.

**Comment by rmccue** [comment]
> What if the conversion goal for one variant is just the default view and another is a click on something.

We can highlight that to users to inform them, but it's entirely possible that they _want_ the ability to have different goals. e.g. comparing (in an A/B test) performance of a button vs a link.

> The fallback could legitimately contain nothing. What if one variant has a conversion goal and another doesn't? Does that matter?

I think that's fine, and we can inform the user, but we don't need to force them. We want to guide users towards things, but we shouldn't remove their ability to make the tool work for them. Also:

> I'd like to believe, there will always be a fallback content.

That might not be the case, and there might be good reasons not to. You might want to show some content only to certain audiences, with no content at all for others.

Take for example geotargeting for an event (my favourite example). Imagine you're running an event in the UK and France, and for the users in those countries, you want to display the event. For everyone else though, maybe you don't want to display anything at all. That's a perfectly valid use case, and you don't need an action in the fallback at all. Or, maybe you want to show a special CTA for repeat visitors to a site, but nothing at all for first time visitors.

**Comment by PriyaBhatia0210** [comment]
> Or, maybe you want to show a special CTA for repeat visitors to a site, but nothing at all for first time visitors.

Could you elaborate more on this point @rmccue ?
For first time visitors your 'nothing' is a Fallback variant and for the repeat amongst those is the audience that will see a special CTA variant. Thus, there will be a fallback variant in this case at least. That's how I am thinking.

**Comment by roborourke** [comment]
Completed in https://github.com/humanmade/experiments/pull/49
