### ISSUE TITLE
XB Analytics: Provide a way to see total unique views of an XB variant

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#77]
Surfacing data collected from #75  

## User Story
As a marketer, I would like to see the total unique views of each XB variant, so that I can see the total impressions on the XB variant 

## Requirements
1. The ability to see the total views of the selected XB per the views collected in #75 inline in the XB editor page

## Acceptance Criteria
Given: I am logged in as a marketer in /wp-admin/
And: I want to see the total views of an XB variant 
When: I select an XB in the XB editor 
Then: I should be able to see total views of the XB variant as collected in #75 inline on the right hand sidebar along with the total page views

**Comment by PriyaBhatia0210** [comment]
For this, I am thinking whether we can add another section to the 'Document' and 'Block' sidebar that reads "Page Analytics".

This section can then show the: total page views, total XB views, CTA conversions per variant when that variant is selected. 

Thoughts?

**Comment by roborourke** [comment]
It could be a useful overview for sure, only thing to be wary of is that with each new thing it's increasing the scope and work required to complete the issue. It could be split out - we ideally have issues that are granular enough to pave the way to a good MVP and define next steps & improvements.

**Comment by PriyaBhatia0210** [comment]
So when we say the views will be shown inline, what do we exactly mean? Where will these page and XB views be surfaced in the admin?

>It could be split out - we ideally have issues that are granular enough to pave the way to a good MVP and define next steps & improvements.
Sure. Splitting up issues as we go along. Changed up this one too.🙂
