### ISSUE TITLE
XB Analytics: Metrics to track performance of XBs in a webpage

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#78]
Extension of #76 & #77

## User Story
As a user (content manager), I would like to compare the performance of personalized XB variants (Lift) so that I can track the opportunities and quality leads generated.

## Requirements
1. The ability to compare each CTA conversion rate (how many visitors clicked on each CTA within an XB) with total views of that XB variant
2. The ability to compare total XB views of each variant with page views
3. The ability to compare webpage bounce rate in case of a Fallback variant with bounce rate in case of a personalized XB variant
4. The ability to compare average session length in case of a Fallback variant with average session length in case of a personalized XB webpage 
5. The ability to compare the CTA conversion rate of a Fallback variant with the CTA conversion rate of a personalised XB variant  

## Acceptance Criteria
Given: I am logged in as a content manager in the /wp-admin/
And: I want to understand how my latest XB content has performed
Then: I should be able to pull all of the above metrics

**Comment by PriyaBhatia0210** [comment]
Just noting : I'd also like to add how an XB with a CTA performed vs an XB without a CTA to prompt a user to always attach a CTA to an XB. Cant think of a metric at the moment.

**Comment by roborourke** [comment]
> Just noting : I'd also like to add how an XB with a CTA performed vs an XB without a CTA to prompt a user to always attach a CTA to an XB. Cant think of a metric at the moment.

If we're not tracking any sort of conversion for certain XBs then there's nothing to compare against performance wise so I'm not sure where the value in this would be or how it could be done. Also different conversion goals won't be strictly comparable, as it's different content, different purpose / audiences and so on.

I suggest we treat Views / Impressions as the default conversion goal.

Side note I'd prefer if we kept the language as referring to conversion goals rather than CTAs. CTAs are an explicit thing like a button or link etc... a goal is more flexible and a commonly used term in other analytics tools.

**Comment by roborourke** [comment]
Can you clarify something for me?

> The ability to count only unique views per account / user / IP irrespective of the no. of user sessions.

Does this mean we should let people decide whether to see unique views instead like some sort of toggle or that it should always reflect uniques? 

> The ability to block internal employee views count under total XB variant views

This requirement should be a separate issue.

**Comment by jennybeaumont** [comment]
To split out 6 & 7 into separate tickets
>The ability to block internal employee views count under total XB variant views
>The ability to count only unique views per account / user / IP irrespective of the no. of user sessions.

**Comment by PriyaBhatia0210** [comment]
>The ability to block internal employee views count under total XB variant views

New issue here #98 

>The ability to count only unique views per account / user / IP irrespective of the no. of user sessions. 

New issue here #99

**Comment by roborourke** [comment]
I feel like we've pretty much covered this one now with the single XB metrics view in #120 

We're missing requirements 3 and 4 but I'm not sure how useful those are compared to direct conversion rate, there are a lot of factors that affect the usefulness of bounce rate and time on page.

Feel free to reopen if needed but might be better to create a new more focused issue for anything else.
