### ISSUE TITLE
XB Analytics: Provide a way to view conversion goal metrics related to an XB variant 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#81]
Surfacing data collected through #76

## User Story
As a marketer, I would like to view the metrics related to a CTA conversion goal that I added in a XB variant, so that I can see the total impressions on the XB variant 

## Requirements
1. The ability to view each CTA conversion count when the block is selected inline in the editor sidebar 

## Acceptance Criteria
Given: I am logged in as a marketer in /wp-admin/
And: I want to view CTA conversion metrics of the XB variant 
When: I select an XB in the XB editor 
Then: I should be able to see the CTA conversion count of a XB variant inline on the right hand sidebar along with the total page views

**Comment by jennybeaumont** [comment]
Covered in https://github.com/humanmade/altis-analytics/issues/76
