### ISSUE TITLE
Audience size can show values >100%

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-analytics#88]
Occasionally when in the audience builder with no conditions set, the audience size can incorrectly show values greater than 100%. Usually these are close to 100% (i.e. 101%) but I have seen higher as well.

Unclear currently on how to reproduce this, but I've definitely had it happen a few times while demoing the audience builder features. This could be a cache inconsistency.

Steps to reproduce:
1.

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
Definitely happening with the latest version? I remember adding some cache clearing logic a while ago to address this when it was originally reported.

**Comment by rmccue** [comment]
I'll get back to you, but I've seen it fairly recently.
