### ISSUE TITLE
Referrer Attribute Contains in Audiences Not Working

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#92]
Steps to reproduce:
1. Create a new Audience and select Referrer
1. Enter "contains" and try something like ".com" / "google" etc
1. Results show 0, even though if I select "is" and "https://google.com" it shows 43%.

![](https://joehoyle-captured.s3.amazonaws.com/Screen-Shot-2020-11-23-14-24-25.51-69wpBre4lPIuNKnBraaP6pBhtoeveZFWEhDtIOhisSc3ulHqOBXjXM9FREpYTtIrNucW9u7CgDAIcdqzLhM5FvyrW1OuO3GbzYEX.png)

Acceptance criteria:

- [ ] "contains" should partial match against referrers

**Comment by roborourke** [comment]
This might be an elasticsearch query issue expecting a prefix match. Will look into it.

**Comment by joehoyle** [comment]
Ah, this _might_ have not fixed its self. We were having memory issues with ES, which have been fixed. I'm now seeing "contains" with freeform values working., I think maybe this is just a more complex ES query so I was hitting those memory limits. Closing for now.

**Comment by roborourke** [comment]
Thought it was odd. Maybe wildcard queries are a bit too much. What are the implications regarding memory usage? Do we need to make some updates to the infrastructure to handle that or was it because the older indexes hadn’t been removed yet?

**Comment by joehoyle** [comment]
This was due to https://dashboard.altis-dxp.com/#/support/ticket/4283/ where I believe there was a bug at the infra level.
