### ISSUE TITLE
XB Analytics: User Documentation

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-analytics#94]
For Altis v6 release, XB analytics is starting to look in a good shape with the inclusion of XB variant views and an option to add a conversion goal. We'd like to capture these as User Documentation to explain the ideal user flow to make the most of these features. 

### How to create personalized content:
- [x] Select the personalised content block (aka XB block) from the list of blocks
- [x] Add generic content (aka Fallback variant) that will be shown to general audience 
- [x] Add another personalised block variant
- [x] Select the audience that will be able to see this block from the ride-hand sidebar 
- [x] Add more variants to target your audience appropriately  

### Defining new audience:
- [x] You may select an audience from the Audience selection page that pops up from the right hand sidebar
- [x] In the same page you can "Add new" audiences
- [x] In the "Edit Audience" page, enter the name of the new Audience 
- [x] Create new audiences by choosing rules from the drop downs 
- [x] Switch the new audience to "Active" on the right hand sidebar and the audience is ready to be used in your personalized content   

### Adding a conversion goal to measure engagement:
- [x] Insert a Call to Action in your personalized content
- [x] Choose a conversion goal associated with that personalized block from the dropdown in the right hand sidebar

### Measuring performance
- [x] Once you have added personalized content and audiences to your webpages and have published the same, you'll be able to see the no of XB views per variant on the right hand side bar
- [x] If you added a conversion goal as well to your personalized content blocks, you will be able to see the percentage conversion against the no. of views of each block
- [ ] To compare how well your personalized content performing you must always add a fallback variant to compare these metrics against the generic content

**Comment by PriyaBhatia0210** [comment]
Might be nice to include a flowchart such as the following. Let me know if you need help creating this for the user docs:

![image](https://user-images.githubusercontent.com/55112796/100279645-f202b280-2f34-11eb-9b56-c5acf2b8ab8c.png)

**Comment by roborourke** [comment]
Fixed by #105
