### ISSUE TITLE
Removing audience attribute causes subsequent cases to be converted to dropdowns

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#95]
Steps to reproduce:
1. Add a new audience with one attribute based off known values (dropdown), and a second criteria based off Customer value (free form text). 
1. Delete the first criterea

Video: https://joehoyle-captured.s3.amazonaws.com/audience-remove-critera-IFC8lGSJWPNbf5v5k66mbVPZuBznwa7nAfzHpRQAL1DE0rcCFG6M56Gu6FEqi9Pnsgv4pOeJkSGqScuAWmWQ89ko71GXJwjPOHe6.mov

**Comment by roborourke** [comment]
Fixed by https://github.com/humanmade/aws-analytics/pull/144
