### ISSUE TITLE
Audiences based off Referrer are not "sticky"

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-analytics#97]
At the moment, it seems audiences based off Referrer (and maybe UTM source stuff too) is only based off the immediate first page view. For example, I have an audience called "Developers" that matches based off Referrer:github.com. My expectations is that if someone lands from GitHub the first time, they are permanently in that audience. Right now `Altis.Analytics.getAudiences()` only returns by Developers audience on the first page view.

For Referrer and UTM compaigns I'm not really sure if the immediate page view is that valuable. As a marketer, I want to be able to segment by users by demographic, and that applies to the lifetime of their session, not just the immediate click-through.

**Comment by roborourke** [comment]
Been wondering about this. Pinpoint itself only supports using endpoint data for segments and I think we’ll need to sync audiences there at some point. We could start putting referrers and utm data into the endpoint attributes instead to make them sticky. Right now you’d need to add some front end code to that.

**Comment by PriyaBhatia0210** [comment]
Seems similar to https://github.com/humanmade/aws-analytics/issues/58 that we refined last week.

Shall we close this? @roborourke

**Comment by roborourke** [comment]
Yeah, this one mentioned referrer and the other UTM parameters but the solution is the same 👍
